export const ROUTES = {
  LOGIN: '/login',
  INSCRIPTION: '/inscription',
  SET_PASSWORD: '/set-password',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/',
  DIRECTIONS: '/directions',
  AGENTS: '/agents',
  MANAGERS: '/managers',
  CONSULTATION: '/consultation',
  RAPPORTS: '/rapports',
  SIMULATION: '/simulation',
  VALIDATIONS: '/validations',
  EMPLOYES_DIRECTION: '/employes-direction',
  INVITATIONS: '/invitations',
  INCIDENTS: '/incidents',
  DOSSIERS_N2: '/dossiers-n2',
  INCIDENTS_SURETE: '/incidents-surete',
  HISTORIQUE: '/historique',
  MA_DEMANDE: '/ma-demande',
  MON_HISTORIQUE: '/mon-historique',
  PARAMETRES: '/parametres',
}
