server.port=8081
spring.application.name=Backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sigba_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak / OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/sigba-realm

# Keycloak Admin API (création de comptes)
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=sigba-realm
keycloak.admin.client-id=sigba-backend
keycloak.admin.client-secret=
keycloak.admin.username=admin
keycloak.admin.password=admin

# Logging
logging.level.ma.ram.sigba=INFO
logging.level.org.hibernate.SQL=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n